<?php

use Illuminate\Database\Seeder;

class DvsPageVersionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('dvs_page_versions')->insert(array (
            0 =>
            array (
                'page_id' => 1,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'page_id' => 2,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'page_id' => 3,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'page_id' => 4,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'page_id' => 5,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'page_id' => 6,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'page_id' => 7,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'page_id' => 8,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'page_id' => 9,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'page_id' => 10,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'page_id' => 11,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'page_id' => 12,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'page_id' => 13,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'page_id' => 14,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'page_id' => 15,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'page_id' => 16,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'page_id' => 17,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'page_id' => 18,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'page_id' => 19,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'page_id' => 20,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'page_id' => 21,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'page_id' => 22,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'page_id' => 23,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'page_id' => 24,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'page_id' => 25,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            25 =>
            array (
                'page_id' => 26,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            26 =>
            array (
                'page_id' => 27,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            27 =>
            array (
                'page_id' => 28,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            28 =>
            array (
                'page_id' => 29,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            29 =>
            array (
                'page_id' => 30,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            30 =>
            array (
                'page_id' => 31,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            31 =>
            array (
                'page_id' => 32,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            32 =>
            array (
                'page_id' => 33,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            33 =>
            array (
                'page_id' => 34,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            34 =>
            array (
                'page_id' => 35,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            35 =>
            array (
                'page_id' => 36,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            36 =>
            array (
                'page_id' => 37,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            37 =>
            array (
                'page_id' => 38,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            38 =>
            array (
                'page_id' => 39,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            39 =>
            array (
                'page_id' => 40,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            40 =>
            array (
                'page_id' => 41,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            41 =>
            array (
                'page_id' => 42,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            42 =>
            array (
                'page_id' => 43,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            43 =>
            array (
                'page_id' => 44,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            44 =>
            array (
                'page_id' => 45,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            45 =>
            array (
                'page_id' => 46,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            46 =>
            array (
                'page_id' => 47,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            47 =>
            array (
                'page_id' => 48,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            48 =>
            array (
                'page_id' => 49,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            49 =>
            array (
                'page_id' => 50,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            50 =>
            array (
                'page_id' => 51,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            51 =>
            array (
                'page_id' => 52,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            52 =>
            array (
                'page_id' => 53,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            53 =>
            array (
                'page_id' => 54,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            54 =>
            array (
                'page_id' => 55,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            55 =>
            array (
                'page_id' => 56,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            56 =>
            array (
                'page_id' => 57,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            57 =>
            array (
                'page_id' => 58,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            58 =>
            array (
                'page_id' => 59,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            59 =>
            array (
                'page_id' => 60,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            60 =>
            array (
                'page_id' => 61,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            61 =>
            array (
                'page_id' => 62,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            62 =>
            array (
                'page_id' => 63,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            63 =>
            array (
                'page_id' => 64,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            64 =>
            array (
                'page_id' => 65,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            65 =>
            array (
                'page_id' => 66,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            66 =>
            array (
                'page_id' => 67,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            67 =>
            array (
                'page_id' => 68,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            68 =>
            array (
                'page_id' => 69,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            69 =>
            array (
                'page_id' => 70,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            70 =>
            array (
                'page_id' => 71,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            71 =>
            array (
                'page_id' => 72,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            72 =>
            array (
                'page_id' => 73,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            73 =>
            array (
                'page_id' => 74,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            74 =>
            array (
                'page_id' => 75,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            75 =>
            array (
                'page_id' => 76,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            76 =>
            array (
                'page_id' => 77,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            77 =>
            array (
                'page_id' => 78,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            78 =>
            array (
                'page_id' => 79,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            79 =>
            array (
                'page_id' => 80,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            80 =>
            array (
                'page_id' => 81,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            81 =>
            array (
                'page_id' => 82,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            82 =>
            array (
                'page_id' => 83,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            83 =>
            array (
                'page_id' => 84,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            84 =>
            array (
                'page_id' => 85,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            85 =>
            array (
                'page_id' => 86,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            86 =>
            array (
                'page_id' => 87,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            87 =>
            array (
                'page_id' => 88,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            88 =>
            array (
                'page_id' => 89,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            89 =>
            array (
                'page_id' => 90,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            90 =>
            array (
                'page_id' => 91,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            91 =>
            array (
                'page_id' => 92,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            92 =>
            array (
                'page_id' => 93,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            93 =>
            array (
                'page_id' => 94,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            94 =>
            array (
                'page_id' => 95,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            95 =>
            array (
                'page_id' => 96,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            96 =>
            array (
                'page_id' => 97,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            97 =>
            array (
                'page_id' => 98,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            98 =>
            array (
                'page_id' => 99,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            99 =>
            array (
                'page_id' => 100,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            100 =>
            array (
                'page_id' => 101,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:19:42',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            101 =>
            array (
                'page_id' => 102,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:34:53',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            102 =>
            array (
                'page_id' => 103,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:34:53',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            103 =>
            array (
                'page_id' => 104,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:34:53',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            104 =>
            array (
                'page_id' => 105,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:34:53',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            105 =>
            array (
                'page_id' => 106,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:34:53',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
            106 =>
            array (
                'page_id' => 107,
                'created_by_user_id' => 1,
                'name' => 'Default',
                'view' => NULL,
                'starts_at' => '2017-07-27 03:34:53',
                'ends_at' => NULL,
                'ab_testing_amount' => 0,
                'preview_hash' => NULL,
                'deleted_at' => NULL,
            ),
        ));


    }
}
